### ISSUE TITLE
pushしようとするとpermissionエラーがでる

### ISSUE THREAD

**Issue by fukatetsu** [iskhas/Ripple-iskhas#9]
作成したブランチをリモートにプッシュしようとすると、下記エラーが出る
↓エラーメッセージ
You don't have permissions to push to "iskhas/Ripple-iskas" on GitHub. Would you like to create a fork and push to it instead?

folkを作った後にupstreamにpushしようとしても失敗する。

保護設定や権限を見直してほしいです。
iskhasのメンバーには追加されています。

https://urashita.com/archives/16808
↑ググったらでてきたもの。参考になるかは不明

**Comment by iskhas-hq** [comment]
@fukatetsu adminに深津さんを加えておきました。push確認できたらクローズしてください。

**Comment by fukatetsu** [comment]
使用していたアカウントとUpstreamの設定の問題でした
解決できました。
